#!/bin/bash

<<DESCRIPTION
  Pick a day that's best for a date
DESCRIPTION

# catch errors
set -ue

# set color variables
RESTORE='\033[0m'
RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'
BLUE='\033[00;34m'
PURPLE='\033[00;35m'
CYAN='\033[00;36m'
LIGHTGRAY='\033[00;37m'
LRED='\033[01;31m'
LGREEN='\033[01;32m'
LYELLOW='\033[01;33m'
LBLUE='\033[01;34m'
LPURPLE='\033[01;35m'
LCYAN='\033[01;36m'
WHITE='\033[01;37m'

# set command
OPEN="open -a 'Google Chrome.app'"

printf "\n\n${LCYAN}What day would you like a date with this carefully woven, meticulously threaded, and sturdy sac? Choose wisely...\n\n\n${RESTORE}"
select day in "Monday" "Tuesday" "Wednesday" "Thursday" "Friday" "Never" "Boner Face"; do
    case $day in
      Monday ) URL="http://www.youtube.com/watch?v=h-amxmcNjfo";
        eval $OPEN $URL;;
      Tuesday ) URL="http://cdn.memegenerator.net/instances/500x/32398338.jpg";
        eval $OPEN $URL;;
      Wednesday ) URL="http://youtu.be/rHG-JO8gIGk?t=54s";
        eval $OPEN $URL;;
      Thursday ) URL="http://www.youtube.com/watch?v=rEVKInsam9s"; 
        eval $OPEN $URL;
        exit;; 
      Friday ) URL="http://cdn.memegenerator.net/instances/500x/32424970.jpg"; 
        eval $OPEN $URL;;
      Never ) URL="http://cdn.memegenerator.net/instances/500x/31834594.jpg"; 
        eval $OPEN $URL;;
      "Boner Face" ) URL="http://i1.kym-cdn.com/photos/images/original/000/140/121/flcl-meme-generator-i-have-the-weirdest-boner-cdaed9.jpg"; 
        eval $OPEN $URL;;
    esac
done
