#!/usr/bin/env bash

set -euo pipefail

# create file
touch $( pwd )/Makefile

# add lines to file
echo "# Makefile for data analysis

## VARIABLES -------------------------------------------------------------------


## HELP ------------------------------------------------------------------------
help:
	@echo 'Makefile for a data analysis workflow'
	@echo ''
	@echo 'Usage:'
	@echo '    make help           display this help message'
	@echo ''


## RUN ALL ---------------------------------------------------------------------
all: 


## CLEAN -----------------------------------------------------------------------
clean: 


.PHONY: help all clean" > $( pwd )/Makefile

exit
