#!/bin/bash
#===============================================================================
#
#          FILE:  password
# 
#         USAGE:  ./password [ length ]
# 
#   DESCRIPTION:  Generate a secure password using /dev/urandom
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#       VERSION:  1.0
#       CREATED:  10/13/2009 11:10:39 CDT
#      REVISION:  ---
#===============================================================================
 
function usage () {
cat <<EOS
    Usage: `basename $0` [ length ] [ --usage | --help ]
    Default password length is 12
EOS
 
}
 
while [ ! -z $1 ]
do
  case $1 in 
    '--usage')
      usage
      exit
      ;;
    '--help')
     usage
     exit
      ;;
    *)
    length=$1
    [[ $length -lt 1 ]] && {
      usage
      exit
    } 
    ;;
  esac 
  shift
done
 
[[ -z $length ]] && length=12
[[ $length -lt 4 ]] && {
  echo password is too weak to produce
  exit 1
}
[[ $length -lt 8 ]] && {
  echo password is weak
}
declare password
while [[ ${#password} -lt $length ]]
do
  char=`dd if=/dev/urandom bs=1 count=1 2> /dev/null | mimencode`
  char=${char:0:1}
  password="$password$char"
done
echo $password
